### PR TITLE
Check minimum vagga version before validating config

### PR DESCRIPTION
**Pull request by anti-social**

### CODE REVIEW

**Comment by tailhook** [comment]
Looks fine, except you shouldn't parse configuration again. Use already parsed AST.

**Comment by anti-social** [comment]
Probably it is worth to add a function into `rust-quire` that accepts AST and validate it? Otherwise there will be too much copy-paste.

**Comment by tailhook** [comment]
> Probably it is worth to add a function into rust-quire that accepts AST and validate it?

I'm not sure this is exact semantic it should have. But yes, the whole idea is to split `parse_config` into smaller parts. That was always intended to be a quick shortcut, until you have more specific needs.

Just got another thought: it may be worth to implement version check as a validator. Since the validators are executed at the AST stage, it may work as good as this hack.

**Comment by anti-social** [comment]
Can't understand why `gem bundler lock` test fails. It passes on my local machine.

**Comment by tailhook** [comment]
I don't know either. Probably error is somewhat transient.

Merged. Thanks!

**Pull request merged**
