### PR TITLE
Set file permissions in copy tests, fixed copy tests for travis

### PR DESCRIPTION
**Pull request by anti-social**

### CODE REVIEW

**Comment by tailhook** [comment]
What makes it stil fail on directory test? Is do you have to set directory permissions too?

**Comment by anti-social** [comment]
Can't set directory permissions. Test fails and I get strange behavior:

```
$ ls -l tests/copy/dir/
ls: cannot access tests/copy/dir/second: Permission denied
ls: cannot access tests/copy/dir/hello: Permission denied
ls: cannot access tests/copy/dir/subdir: Permission denied
total 0
-????????? ? ? ? ?            ? hello
-????????? ? ? ? ?            ? second
d????????? ? ? ? ?            ? subdir
$ sudo ls -l tests/copy/dir/
итого 12
-rw-r--r-- 1 alexk alexk    6 Фев  2 23:34 hello
-rw-r--r-- 1 alexk alexk    5 Фев  2 23:34 second
drw-r--r-- 2 alexk alexk 4096 Фев  2 23:34 subdir
```

**Comment by tailhook** [comment]
Sure, you need to turn executable bit on. I.e. 755 instead of 644 on a directory

**Comment by anti-social** [comment]
Stupid me =)

**Comment by anti-social** [comment]
Works

**Comment by tailhook** [comment]
Fine. Thanks!

**Pull request merged**
