### PR TITLE
Basic autocomplete for vagga

### PR DESCRIPTION
**Pull request by anti-social**

### CODE REVIEW

**Comment by tailhook** [comment]
Wow! Looks great. We need some docs, though.

**Comment by lilianmoraru** [comment]
`install: cannot stat ‘vagga-completion.sh’: No such file or directory` - when installing `vagga-testing`

**Comment by tailhook** [comment]
Hopefully fixed 709a9bf . I'm in the airport now. So will verify it later.

**Comment by tailhook** [comment]
@lilianmoraru new version is already in testing. Could you check if installation works fine?

If not, please open a separate issue, so we can track it easier. Thanks!

**Comment by lilianmoraru** [comment]
@tailhook Yes, installed ok.

**Comment by tailhook** [comment]
@lilianmoraru Thanks!

**Pull request merged**
