### PR TITLE
Fix removing symlink to a directory when processing data-dirs option

### PR DESCRIPTION
**Pull request by anti-social**

### CODE REVIEW

**Comment by anti-social** [comment]
@tailhook Could you review this PR

**Comment by tailhook** [comment]
It's fine. But I don't understand why tests fail :(

**Comment by anti-social** [comment]
It looks like `pip` bumped minimum supported python version to 3.7:
```
ERROR: This script does not work on Python 3.6 The minimum supported Python version is 3.7. Please use https://bootstrap.pypa.io/pip/3.6/get-pip.py instead.
```

**Comment by tailhook** [comment]
Ah, well, this is a new failure. So previous was probably some multi-day hiccup of github :(

**Pull request merged**
