### PR TITLE
Add volumes option for commands

### PR DESCRIPTION
**Pull request by anti-social**

### CODE REVIEW

**Comment by tailhook** [comment]
Looks fine. Merged.

**Comment by lilianmoraru** [comment]
Could we also get documentation about this feature, please?

**Comment by tailhook** [comment]
I've added some docs (http://vagga.readthedocs.org/en/latest/commands.html#opt-volumes). But overall I must be more rigorous and require documentation for these features.

**Comment by lilianmoraru** [comment]
Thanks

**Pull request merged**
