### PR TITLE
Ubuntu non lts

### PR DESCRIPTION
**Pull request by simon-bourne**
Hey, here's the code so far for using non lts ubuntu. We still need to decide about what to do about the name/version both needing to be specified, but for now I'd appeciate any feedback on my rust code (it's the first time I've written any rust, so feel free to be critical)!

### CODE REVIEW

**Comment by tailhook** [comment]
From the first glance it lot ok. You don't need `concat!()`, it's possible to do wrap lines with slashes in current rust. (But I understand that my code was like so).

I take some time to think again about whether we want to require "name", because it's backward-compatibility issue.

**Comment by simon-bourne** [comment]
Let me know what conclusions you come to. I found /etc/lsb-release which is in the cd images and is exactly what I want. I was only planning on looking at it when processing !UbuntuRelease, not !Ubuntu, so it shouldn't break anything out there already. The other thing to consider is do you want UbuntuRelease to look like this:

!UbuntuRelease { version: 14.10 }

or

!UbuntuRelease 14.10

I'm not too fussed which, but I'd slightly favour the first as it leaves the door open for future enhancments:

!UbuntuRelease { version: 14.10, kind: ... , arch: ... }

So you've got a "I just want an LTS Ubuntu" with !Ubuntu, and " I want to be more specific about ubuntu versions" with !UbuntuVersion, that can be extended.

**Comment by tailhook** [comment]
Looks nice. Thanks! And yes, I like the extensible form.

**Comment by simon-bourne** [comment]
Great, thanks!

**Pull request merged**
