### PR TITLE
New hashes

### LINKED ISSUE #366: Invalid calculations of uidmap
Here is relevant panic.
```$ vagga _clean --unused
thread '<main>' panicked at 'arithmetic operation overflowed', src/config/range.rs:52
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

This is a bug in range calculations. Fixing it in most straightforward and sensible way means changing hashes of all containers.

We can either patch only this and keep technical debt by hardcoding `-1` in hash function. Or fix it in most sensible way and require everyone to rebuild (all hashes will change). If we choose latter we might take a step further to clean up technical debt from all command hash functions.

/cc @anti-social

### PR DESCRIPTION
**Pull request by tailhook**
As an excuse to fix #366 while breaking hashes I'm going to refactor all the hashing code and implement some debug log for the hashed data.

ping @anti-social

### CODE REVIEW

**Comment by anti-social** [comment]
Are you going to add build step names into hash?

**Comment by tailhook** [comment]
> Are you going to add build step names into hash?

Yes. Just got no time to do it overnight :)

**Comment by tailhook** [comment]
Done. @anti-social any other suggestions?

**Comment by anti-social** [comment]
Really great job!

**Pull request merged**
